# Generated by Django 3.2.12 on 2022-04-14 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=150, verbose_name='Make')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('year', models.IntegerField()),
                ('license', models.CharField(max_length=150, verbose_name='License plate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parking Name')),
                ('parking_address', models.CharField(max_length=250)),
                ('parking_zip', models.CharField(max_length=8, verbose_name='Zip Code')),
                ('parking_city', models.CharField(max_length=50, verbose_name='City')),
                ('parking_state', models.CharField(max_length=50, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('col', models.IntegerField()),
                ('cost_per_hour', models.IntegerField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.car')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.parking')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
