# Generated by Django 3.2.12 on 2022-03-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=150, verbose_name='Make')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('year', models.DateTimeField()),
                ('license', models.CharField(max_length=150, verbose_name='License plate')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parking Name')),
                ('parking_address', models.CharField(max_length=250)),
                ('parking_zip', models.CharField(max_length=8, verbose_name='Zip Code')),
                ('parking_city', models.CharField(max_length=50, verbose_name='City')),
                ('parking_state', models.CharField(max_length=50, verbose_name='State')),
                ('parking_sports', models.IntegerField()),
                ('free_parking_spots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.car')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingReservation.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
