# Generated by Django 3.2.12 on 2022-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingReservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
