# Generated by Django 3.2.12 on 2022-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingReservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(),
        ),
    ]
