# Generated by Django 3.2.12 on 2022-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingReservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
