# Generated by Django 3.2.12 on 2022-04-04 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingReservation', '0002_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parking_sports',
            new_name='parking_spots',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
