# Generated by Django 3.2.12 on 2022-03-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingReservation', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
